# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 너드팩토리 기술 블로그
email: "contact@nerdfactory.ai"
image: "https://blog.nerdfactory.ai/assets/images/posts/branding-nerdfactory/img2.png"
description: >- # this means to ignore newlines until "baseurl:"
  너드팩토리에서 운영하는 기술블로그 입니다.
phone: "+82 (042) 827 9715"
copyright: "Copyright 2018 @ NerdFactory. All Right Reserved."
name: "너드팩토리"

baseurl: ""
url: "https://blog.nerdfactory.ai"
#twitter_username: jekyllrb
#github_username:  jekyll

repository: "NerdFactoryAI/nerdfactoryai.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
